cost_publisher:
    ros__parameters:
        # ros
        use_sim_time: On 

        cost_stats_dir: "cost_configs/wanda_cost_statistics.yaml"

        cost_topic: "/traversability_cost"
        cost_array_topic: "/traversability_breakdown"
        cost_baseline_topic: "/traversability_cost_baseline"
        speed_mismatch_topic: "/speed_mismatch"

        imu_topic: "/novatel/imu/data"    
        odom_topic: "/superodometry/integrated_to_init"
      
        shock_topic: "/shock_pos"
        joy_topic: "/joy"
        terrain_mismatch_topic: "/terrain_mismatch"


dino_costmap_gp_speed_input_output:
    ros__parameters:
        # ros
        use_sim_time: On 

        # node specific
        config_file: "costmap_configs/GP_base.yaml"
        cost_topic: "/traversability_cost" 
        odom_topic: "/superodometry/integrated_to_init"           

        gridmap_topic: "/dino_gridmap"
        costmap_topic: "/shortrange_costmap"
        speedmap_topic: "/shortrange_speedmap"
        cvar_speedmap_topic: "/hdif_speedmap_cvar"

        hdif_max_roughness_topic: "/hdif_max_roughness"
        hdif_cvar_topic: "/hdif_cvar"
        vel_pub_topic: "/controller/target_input"        